<jsp:include page="/templates/header.jsp" />

<div class="container">
    <h3>Datos Personales</h3>
    <form action="home" method="post">
        <div class="form-group">
            <label for="firstname">Nombre</label>
            <input type="text" class="form-control" name="firstname">
        </div>
        <div class="form-group">
            <label for="lastname">Apellido</label>
            <input type="text" class="form-control" name="lastname">
        </div>
        <button type="submit">Mostrar datos</button>
    </form>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque eu ultrices vitae auctor eu augue ut. Cras pulvinar mattis nunc sed blandit libero. Egestas dui id ornare arcu odio. Nibh venenatis cras sed felis eget velit aliquet sagittis id. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. At in tellus integer feugiat scelerisque varius morbi enim. Morbi tempus iaculis urna id. Volutpat odio facilisis mauris sit amet massa vitae tortor. Aliquam vestibulum morbi blandit cursus risus. Mauris rhoncus aenean vel elit scelerisque.</p>
    <p>Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Amet nisl suscipit adipiscing bibendum est ultricies integer. Nibh venenatis cras sed felis eget velit aliquet sagittis. Ipsum dolor sit amet consectetur adipiscing elit ut. Eget egestas purus viverra accumsan in nisl. Leo vel orci porta non pulvinar neque. Varius vel pharetra vel turpis nunc eget. Mi tempus imperdiet nulla malesuada pellentesque. Turpis tincidunt id aliquet risus feugiat in ante metus. Maecenas ultricies mi eget mauris. Duis tristique sollicitudin nibh sit. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Et magnis dis parturient montes nascetur ridiculus mus.</p>
    <p>Tincidunt lobortis feugiat vivamus at augue eget arcu. Convallis convallis tellus id interdum velit laoreet. Ut tellus elementum sagittis vitae et leo duis ut. Urna cursus eget nunc scelerisque viverra mauris in aliquam. Mi eget mauris pharetra et ultrices neque ornare. Ut lectus arcu bibendum at varius. Lorem ipsum dolor sit amet consectetur. Sollicitudin tempor id eu nisl nunc mi ipsum. Diam in arcu cursus euismod quis viverra. Sed risus ultricies tristique nulla aliquet enim tortor at. Nunc aliquet bibendum enim facilisis gravida neque convallis. Vel pharetra vel turpis nunc eget lorem dolor. Velit scelerisque in dictum non consectetur a erat. Lectus arcu bibendum at varius vel. Pulvinar mattis nunc sed blandit libero volutpat.</p>
    <p>Arcu bibendum at varius vel pharetra vel turpis nunc. Adipiscing elit ut aliquam purus sit amet. Amet justo donec enim diam vulputate ut pharetra sit amet. Commodo viverra maecenas accumsan lacus vel. Amet nulla facilisi morbi tempus iaculis. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Ipsum a arcu cursus vitae congue mauris rhoncus. Mauris commodo quis imperdiet massa tincidunt. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Vivamus at augue eget arcu dictum varius duis. Massa massa ultricies mi quis hendrerit dolor magna. Turpis massa tincidunt dui ut ornare lectus sit. Diam in arcu cursus euismod quis viverra nibh. Id diam maecenas ultricies mi eget mauris pharetra. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Sed odio morbi quis commodo odio aenean.</p>
    <p>Amet facilisis magna etiam tempor. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Nisl nisi scelerisque eu ultrices. Sed pulvinar proin gravida hendrerit. Nisi est sit amet facilisis magna. Sit amet consectetur adipiscing elit ut aliquam purus. Quisque non tellus orci ac auctor augue mauris augue. Sit amet nisl purus in mollis. Consequat ac felis donec et odio. A diam maecenas sed enim ut sem viverra. Condimentum lacinia quis vel eros donec ac odio. Sit amet cursus sit amet dictum sit amet.</p>
    <p>Ipsum suspendisse ultrices gravida dictum fusce ut placerat. Interdum varius sit amet mattis vulputate enim nulla aliquet. Quisque id diam vel quam. Nisl nisi scelerisque eu ultrices vitae auctor eu. Nulla aliquet enim tortor at auctor urna. Aliquet nibh praesent tristique magna sit amet purus gravida. Egestas congue quisque egestas diam in. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Sit amet porttitor eget dolor. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Magnis dis parturient montes nascetur ridiculus. Praesent semper feugiat nibh sed pulvinar proin gravida. Rutrum quisque non tellus orci ac auctor augue mauris augue. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Ut placerat orci nulla pellentesque dignissim enim. Venenatis cras sed felis eget velit aliquet. At urna condimentum mattis pellentesque.</p>
    <p>Faucibus in ornare quam viverra orci sagittis eu. Eu sem integer vitae justo eget magna fermentum. Turpis massa tincidunt dui ut. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Non pulvinar neque laoreet suspendisse. Mauris ultrices eros in cursus turpis massa tincidunt. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Nisi lacus sed viverra tellus in hac. Vel risus commodo viverra maecenas accumsan lacus. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Neque vitae tempus quam pellentesque. Mi tempus imperdiet nulla malesuada pellentesque.</p>
    <p>Morbi tempus iaculis urna id volutpat. Massa tincidunt nunc pulvinar sapien et. Mattis enim ut tellus elementum sagittis vitae. Nullam ac tortor vitae purus faucibus ornare suspendisse. Amet nisl suscipit adipiscing bibendum. Penatibus et magnis dis parturient montes. Lacinia quis vel eros donec. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Elit pellentesque habitant morbi tristique senectus. Fermentum iaculis eu non diam. Sodales ut etiam sit amet. Enim tortor at auctor urna nunc id. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Volutpat est velit egestas dui id ornare arcu odio. Vitae tortor condimentum lacinia quis vel eros donec ac. Varius vel pharetra vel turpis. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Suscipit adipiscing bibendum est ultricies integer quis auctor. Pellentesque habitant morbi tristique senectus et netus et. Sed blandit libero volutpat sed cras ornare.</p>
    <p>Massa tempor nec feugiat nisl pretium. Purus faucibus ornare suspendisse sed nisi lacus. Placerat orci nulla pellentesque dignissim enim sit. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Neque volutpat ac tincidunt vitae semper. Sit amet mauris commodo quis imperdiet massa tincidunt nunc. Proin sagittis nisl rhoncus mattis rhoncus. Nulla facilisi cras fermentum odio eu. Nisi quis eleifend quam adipiscing vitae proin. Quam nulla porttitor massa id. Feugiat pretium nibh ipsum consequat nisl. Hac habitasse platea dictumst vestibulum rhoncus est. Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Vulputate ut pharetra sit amet aliquam id.</p>
    <p>Enim facilisis gravida neque convallis a. Convallis aenean et tortor at risus viverra adipiscing at in. Odio morbi quis commodo odio aenean sed. Sed viverra tellus in hac habitasse platea dictumst. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Mauris nunc congue nisi vitae. Dictum varius duis at consectetur. Arcu odio ut sem nulla pharetra diam. Tincidunt ornare massa eget egestas. Nisi vitae suscipit tellus mauris a diam maecenas sed. Tempus egestas sed sed risus pretium quam vulputate dignissim. Consectetur purus ut faucibus pulvinar elementum integer enim. At auctor urna nunc id cursus metus aliquam eleifend. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Urna nunc id cursus metus aliquam.</p>
</div>

<jsp:include page="/templates/footer.jsp" />
